<?php
/**
 * Writes sample PDF and XLSX artefacts to /tmp so that independent parsers
 * (pypdf / openpyxl) can validate them. Used by tools/crossvalidate.py.
 */

declare(strict_types=1);

$root = dirname(__DIR__) . '/admin';
define('APP_PATH', $root . '/app');
define('ROOT_PATH', $root);

spl_autoload_register(static function (string $class) use ($root): void {
    if (!str_starts_with($class, 'App\\')) {
        return;
    }
    $file = $root . '/app/' . str_replace('\\', '/', substr($class, 4)) . '.php';
    if (is_file($file)) {
        require $file;
    }
});

use App\Core\Config;
use App\Core\Pdf;
use App\Core\Xlsx;

Config::load([
    'app_key' => bin2hex(random_bytes(32)),
    'app'     => ['timezone' => 'Asia/Kolkata'],
]);
date_default_timezone_set('Asia/Kolkata');

$outDir = $argv[1] ?? sys_get_temp_dir();

$headings = ['Loan Account', 'Customer Name', 'Village', 'Outstanding', 'Overdue', 'Status'];
$rows = [];
for ($i = 1; $i <= 60; $i++) {
    $rows[] = [
        'LN' . str_pad((string) $i, 8, '0', STR_PAD_LEFT),
        'Customer ' . $i,
        'Village ' . (($i % 7) + 1),
        1234.5 * $i,
        100.25 * $i,
        $i % 2 === 0 ? 'Pending' : 'Visited',
    ];
}
$totals = ['TOTAL', '', '', 2258235.0, 183457.5, ''];

file_put_contents(
    $outDir . '/lrms_sample.xlsx',
    Xlsx::build('Branch Report', $headings, $rows, 'Branch-wise Report', 'All branches - Jul 2026', $totals)
);

$pdf = new Pdf('Branch-wise Recovery Report', 'All branches - Jul 2026', true, 'D2 Recovery Solutions & Services confidential');
$pdf->setColumns([
    ['label' => 'Loan Account', 'width' => 1.3],
    ['label' => 'Customer',     'width' => 1.6],
    ['label' => 'Village',      'width' => 1.1],
    ['label' => 'Outstanding',  'width' => 1.0, 'align' => 'right'],
    ['label' => 'Overdue',      'width' => 1.0, 'align' => 'right'],
    ['label' => 'Status',       'width' => 0.8],
]);
$pdf->tableHeader();
foreach ($rows as $row) {
    $pdf->row($row);
}
$pdf->totalRow($totals);
$pdf->spacer(10);
$pdf->heading('Notes');
$pdf->paragraph('Generated by the D2 Recovery Solutions & Services PDF writer with no external library. Rupee sign check: Rs. 1,25,000.');

file_put_contents($outDir . '/lrms_sample.pdf', $pdf->output());

echo "written: {$outDir}/lrms_sample.xlsx, {$outDir}/lrms_sample.pdf\n";
